### PR TITLE
vagrant config and provisioning to easily spin up the oauth test app

### PR DESCRIPTION
**Pull request by pho3nixf1re**

### CODE REVIEW

**Comment by el-besto** [comment]
I am not familiar with Vagrant. However, what I did do was clone the repo, checkout this branch and try `vagrant up`.

I then got the following errors: 

screen shot 2015-11-03 at 4 02 22 pm
screen shot 2015-11-03 at 4 02 07 pm

Hopefully that helps.

Additionally, I got an error:

`The guest additions on this VM do not match the installed version of default: VirtualBox`

I know that the `Teachscape/detention` project and the work that has been done by Cristobal for that had some issues on my machine due to this mismatch. He said the version of virtualbox used is very important as the newer software has several breaking changes. Particularly around attaching the VM to the host OS. I think that it would be great to ensure that we are all using the same version of VirtualBox to make this more portable/reusable.

__He wanted me to use `VirtualBox 4.3.x` instead of the newer `5.x` versions.__

Lastly, I hadn't run npm install/start before provisioning on the first go-round, and I also think that impacted the bindings as well. Nothing a README update couldn't fix! Once I did have node running and then re-provisioned (first doing a vagrant destroy to get a clean slate, then vagrant up): 
* `localhost:3000` showed `{"hereThereBe":"nothing","goto":"/auth"}`, and 
* `localhost:3000/auth` showed another error which is likely user error `Tunnel ts-gateway.ngrok.io not found`

Likely user error, but wanted to let you know what I tried and what the results are.

**Comment by pho3nixf1re** [comment]
Those are warnings not actual errors. You can safely ignore them. The port is forwarded to 8080 not 3000. Which is probably not the best idea since it is running on 3000 when you run `npm start`. The `npm install` is going to be incompatible if you run it on your mac since the VM is Linux. The provisioning script removes the node_modules folder on _first run_ only since this is for QA and not for development. I'll add some docs for this tomorrow first thing.

**Comment by pho3nixf1re** [comment]
I'm now thinking that the `node_modules` folder should be scrubbed every time the VM is booted up and `npm install` is re-ran. This prevents accidental issues with osx native `node_modules` being used over the linux ones.

**Comment by pho3nixf1re** [comment]
@el-besto I'm not sure I can control the VM guest additions. This doesn't distribute the VM, only the provisioning. The base VM comes from the official Ubuntu VM images hosted at https://atlas.hashicorp.com/ubuntu. From the looks of your screenshots it doesn't seem to be a problem, so let's not worry about it yet. I would bet that it works just fine for now. In the future we will need to address this somehow. Maybe rolling our own custom boxes and distributing them?

**Comment by el-besto** [comment]
@pho3nixf1re glad that these were not significant issues. I just wanted to let you know them in case they were more significant. As for the custom box, I would be keen to do that, and likely would want to build on what Cristobal has done with Vagrant in the detention repo.

**Pull request merged**
